// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5aaaNXI9qInR70DEZ-R5l7J4ty3T2jSg',
    appId: '1:763306286589:web:af06669bfbb79971530d94',
    messagingSenderId: '763306286589',
    projectId: 'ipssi072023montevrain',
    authDomain: 'ipssi072023montevrain.firebaseapp.com',
    storageBucket: 'ipssi072023montevrain.appspot.com',
    measurementId: 'G-3P6FEV1F86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QnaW89sguCTlXEICYcGRKQ2RTvyi2vg',
    appId: '1:763306286589:android:70726b296d9def4f530d94',
    messagingSenderId: '763306286589',
    projectId: 'ipssi072023montevrain',
    storageBucket: 'ipssi072023montevrain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPzH8Kqvg9pbyjpbN9CGtSyCMjnTNPJFk',
    appId: '1:763306286589:ios:84ff4841dc092a39530d94',
    messagingSenderId: '763306286589',
    projectId: 'ipssi072023montevrain',
    storageBucket: 'ipssi072023montevrain.appspot.com',
    iosClientId: '763306286589-9a1gqefuuslpg8rlqr2omeup2kbv2lnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPzH8Kqvg9pbyjpbN9CGtSyCMjnTNPJFk',
    appId: '1:763306286589:ios:84ff4841dc092a39530d94',
    messagingSenderId: '763306286589',
    projectId: 'ipssi072023montevrain',
    storageBucket: 'ipssi072023montevrain.appspot.com',
    iosClientId: '763306286589-9a1gqefuuslpg8rlqr2omeup2kbv2lnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipssi2023montevrain',
  );
}
